# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  #vmImage: ubuntu-latest
  name: SpartanVMSS

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(1)(da2d52da-2e04-4dd4-b37a-0fea54660754)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'echo "hello"'