# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  #name: SpartanVMSS

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'

- script: |
    curl -sSL https://install.python-poetry.org | python3 -
  displayName: 'Install Poetry'
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- script: |
    cd terraform/
    terraform --version
    terraform init
    terraform plan -out=tfplan
    terraform apply -auto-approve
  displayName: 'Terraform Apply'
