# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  #vmImage: ubuntu-latest
  name: SpartanVMSS

steps:

- script: |
    sudo apt-get -y install unzip
  displayName: 'Install unzip'
  
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

# - task: AzureCLI@0
#   inputs:
#     connectedServiceNameSelector: 'connectedServiceNameARM'
#     connectedServiceNameARM: 'AgenticSVC'
#     scriptLocation: 'inlineScript'
#     inlineScript: |
#           pwd
#           cd terraform/
#           pwd
#           ls -l
#           terraform --version
#           terraform init -reconfigure
#           terraform plan -out=tfplan
#           terraform apply -auto-approve
#     cwd: '$(System.DefaultWorkingDirectory)'

- script: |
    az account set --subscription "da2d52da-2e04-4dd4-b37a-0fea54660754"
    cd terraform/
    terraform --version
    terraform init -reconfigure
    terraform plan -out=tfplan
    terraform apply -auto-approve
  displayName: 'Terraform Apply'
