# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  #vmImage: ubuntu-latest
  name: SpartanVMSS

steps:

- task: TerraformInstaller@2
  inputs:
    terraformVersion: 'latest'

- script: |
    terraform --version
    terraform init
    terraform plan -out=tfplan
    terraform apply -auto-approve
  displayName: 'Terraform Apply'
